import chalk from 'chalk'
import { createPatch } from 'diff'
import { Box, type DOMElement, Text, useBoxMetrics } from 'ink'
import React, { useRef } from 'react'
import { wrapPreviewLines } from './previewLines'

/**
 * Props for the DiffPreview component rendering visual file diffs.
 */
export interface DiffPreviewProps {
  oldText: string
  newText: string
  maxLines?: number
  columns?: number
  filePath: string
}

/**
 * Renders a color-coded unified diff preview of file changes, showing +/-3 context lines and truncating long diffs.
 * @param props The props containing the old text, new text, and path of the file.
 * @returns A JSX.Element showing the formatted unified diff.
 */
export function DiffPreview(props: DiffPreviewProps) {
  const { oldText, newText, filePath, maxLines = 25 } = props
  const ref = useRef<DOMElement>(null)
  const { width } = useBoxMetrics(ref)
  // Generate unified patch with 3 context lines
  const patch = createPatch(filePath, oldText, newText, undefined, undefined, { context: 3 })

  // Split lines and skip the first 4 metadata lines generated by createPatch
  const allLines = patch.split(/\r?\n/)
  const diffLines = allLines.slice(4)
  if (diffLines.at(-1) === '') diffLines.pop()
  const lines = diffLines.map((line) => wrapPreviewLines(line, props.columns ?? Math.max(1, width)))
  const limit = Math.max(0, maxLines)
  const totalRows = lines.reduce((sum, line) => sum + line.length, 0)
  const bodyRows = totalRows > limit ? Math.max(0, limit - 1) : limit
  let used = 0
  const displayedLines: string[] = []
  for (const line of lines) {
    if (used + line.length > bodyRows) break
    displayedLines.push(line.join('\n'))
    used += line.length
  }
  const truncatedCount = diffLines.length - displayedLines.length

  return (
    <Box ref={ref} width="100%" flexDirection="column" flexShrink={0}>
      {width > 0 &&
        displayedLines.map((line, index) => {
          let coloredLine = line

          if (line.startsWith('+') && !line.startsWith('+++')) {
            coloredLine = chalk.green(line)
          } else if (line.startsWith('-') && !line.startsWith('---')) {
            coloredLine = chalk.red(line)
          } else if (line.startsWith('@@')) {
            coloredLine = chalk.cyan(line)
          } else {
            coloredLine = chalk.gray(line)
          }

          return (
            // biome-ignore lint/suspicious/noArrayIndexKey: lines are static and won't change order
            <Text key={index}>{coloredLine}</Text>
          )
        })}
      {width > 0 && truncatedCount > 0 && (
        <Text color="yellow">{`… ${truncatedCount} more diff lines not shown`}</Text>
      )}
    </Box>
  )
}
