import chalk from 'chalk'
import { createPatch } from 'diff'
import { Box, Text } from 'ink'
import React from 'react'

export interface DiffPreviewProps {
  oldText: string
  newText: string
  filePath: string
}

/**
 * Renders a color-coded unified diff preview of file changes, showing +/-3 context lines and truncating long diffs.
 * @param props The props containing the old text, new text, and path of the file.
 * @returns A JSX.Element showing the formatted unified diff.
 */
export function DiffPreview(props: DiffPreviewProps) {
  const { oldText, newText, filePath } = props
  // Generate unified patch with 3 context lines
  const patch = createPatch(filePath, oldText, newText, undefined, undefined, { context: 3 })

  // Split lines and skip the first 4 metadata lines generated by createPatch
  const allLines = patch.split(/\r?\n/)
  const diffLines = allLines.slice(4)

  const MAX_DISPLAY_LINES = 25
  const displayedLines = diffLines.slice(0, MAX_DISPLAY_LINES)
  const truncatedCount = diffLines.length - MAX_DISPLAY_LINES

  return (
    <Box flexDirection="column" marginY={1}>
      {displayedLines.map((line, index) => {
        // Skip trailing empty line if it is the last item
        if (index === displayedLines.length - 1 && line.trim() === '') {
          return null
        }

        let coloredLine = line

        if (line.startsWith('+') && !line.startsWith('+++')) {
          coloredLine = chalk.green(line)
        } else if (line.startsWith('-') && !line.startsWith('---')) {
          coloredLine = chalk.red(line)
        } else if (line.startsWith('@@')) {
          coloredLine = chalk.cyan(line)
        } else {
          coloredLine = chalk.gray(line)
        }

        return (
          // biome-ignore lint/suspicious/noArrayIndexKey: lines are static and won't change order
          <Text key={index}>{coloredLine}</Text>
        )
      })}
      {truncatedCount > 0 && (
        <Text color="yellow">{`... (${truncatedCount} lines truncated)`}</Text>
      )}
    </Box>
  )
}
