export const BASE_GRID = `.................................
.................N...............
................NNN..............
...............t.N...............
......N........t.................
.....NNN.......tT..........N.....
......N.......o.NTo.....ttNNN....
......t....o.....T...o.tt..N.....
......tt..o.....Tn....ot.........
.......ttNTT....B......N.........
........o..n.BBBBBBB...To........
.......o...TBBBBBBBBBTnT.o.......
...........BBBBBBBBBBB...........
..........BBBBBBBBBBBBB..........
..N...o...BBBBBBBBBBBBB...o......
.NNN..TTn.BBBBBBBBBBBBB....ttt...
..N..TN.TBBBBBBBBBBBBBbbT.NT..N..
...ttt....BdBBdBBBdBBdb.nTT..NNN.
......o...BBddBBBBBddbb...o...N..
..........BBBBBBBBBbbbb..........
...........BBBBBBBbbbb...........
.......o.TnTBBBBBbbbbT...o.......
........oT...BBBbbbb.n..o........
.........N......b....TTNtt.......
.........to....nT.....o..tt......
.....N..tt.o...T.....o....t......
....NNNtt.....oTN.o.......N......
.....N..........Tt.......NNN.....
.................t........N......
...............N.t...............
..............NNN................
...............N.................
.................................`.split('\n')

export const OVERLAYS = {
  dim: { x: 13, y: 11, rows: ['...b...', '..bgb..', '...b...'] },
  mid: { x: 13, y: 11, rows: ['..bGb..', 'bgGAGgb', '..bGb..'] },
  bright: { x: 13, y: 10, rows: ['..bbb..', '.bgGgb.', 'bgGAGgb', '.bgGgb.', '..bbb..'] },
} as const
export const PALETTE: Record<string, string> = {
  B: '#E9F2FF',
  b: '#C9D6EA',
  d: '#5F7699',
  g: '#8FDDE6',
  G: '#3FC9D9',
  A: '#E6FFFF',
  T: '#8FA6C8',
  t: '#5F7699',
  o: '#5F7699',
  n: '#FFE7A8',
  N: '#FFC857',
}

export const COMPACT_BASE_GRID = `.................
..N.....NN.......
..N....tt.....NN.
...tT..oNT..tt...
...tN...T..oNT...
....oTBBBBBT.....
.....BBBBBBB.....
.N.T.BBBBBBB.ot..
.NtNTBBBBBBbTNtN.
..to.BdBBBdb.T.N.
.....BBBBbbb.....
.....TBBbbbTo....
...TNo..T...Nt...
...tt..TNo..Tt...
.NN.....tt....N..
.......NN.....N..
.................`.split('\n')

export const COMPACT_OVERLAYS = {
  dim: { x: 8, y: 6, rows: ['g'] },
  mid: { x: 7, y: 6, rows: ['gGg'] },
  bright: { x: 7, y: 5, rows: ['.b.', 'gGg', '.b.'] },
} as const
